baseURL = "https://bkvtest.netlify.com/"
languageCode = "en-gb"
title = "BKVelo"

[params.header]
    title = "BKVelo"
    info = "To Sweet's and Beyond..."
    copyright = "2018 BKVelo.org.uk"

[staticman]
  endpoint = "https://api.staticman.net/v2/entry/"
  username = "mshiner"
  repository = "bkvelo"
  branch = "master"